#!/usr/bin/env fish

set user "__token__"
set pass "$(cat .token)"
set ver "$(cat VERSION)"

echo creating release $ver


rm -rf dist
python setup.py sdist bdist_wheel || exit
python dist_rename.py  || exit

git tag -a $ver || exit
git push origin $ver  || exit

twine upload -u $user -p $pass dist/* || exit
